version: '3'

services:
#    api-service:
#        build: ./flask
#        volumes: 
#            - ./flask:/usr/src/app
#        ports: 
#            - 5001:80

#    api2-service:
#        build: ./flask1
#        volumes: 
#            - ./flask1:/usr/src/app
#        ports: 
#            - 5002:80
#        depends_on: 
#            - api-service
 
#    php-services:
#        image: php:apache
#        volumes: 
#            - ./phpapp:/var/www/html
#            - ./phpapp:/var/www
#        ports: 
#            - 5003:80
#    firefox-service:
#        build: ./firefox
#        environment: 
#            - DISPLAY=${DISPLAY}
#        volumes: 
#            - ./tmp/.X11-unix:/tmp/.X11-unix
#        network_mode: host
#    wireshark-service:
#        build: ./wireshark
#        environment: 
#            - DISPLAY=${DISPLAY}
#        volumes: 
#            - ./tmp/.X11-unix:/tmp/.X11-unix
#        network_mode: host

#    react-services:
#        build: ./reactjsapp
#        #stdin_open: true
#        #tty: true
#        ports: 
#            - "5004:3000"
#        volumes: 
#            - ./reactjsapp/frontend/src:/app/src
#        environment: 
#            - REACT_APP_NAME=test
#        #env_file: 
#        #    - ./reactjsapp/.env